# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Bigflow

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Setup github username
      run: |
        git config --global user.email "fake@example.com"
        git config --global user.name "fake name"
    - name: Setup docker
      run: |
        sudo apt install apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic test"
        sudo apt update
        sudo apt install docker-ce
        docker -v

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install bs4
        pip install pytest
        pip install bigflow
        pip install -r requirements.txt
        pip install -r test/requirements.txt
        sudo apt install docker

    - name: Tests
      run: |
        python -m unittest discover -s bigflow -t . -p '*.py'
        python -m unittest discover -s test -p '*.py'

